#!/bin/bash

# Kiểm tra số lượng arguments
if [ $# -ne 2 ]; then
    echo "Usage: ./runner <hotel_ids> <destination_ids>"
    exit 1
fi

# Execute the Python script with provided arguments
python test.py "$1" "$2"